language: python

python:
    - "2.7"
    - "3.6.8"

before_install:
    - pip install -r requirements.txt
    - pip install codecov

script:
    - invoke test
    - pytest --cov=./

after_success:
    - codecov
